ADD: product 어플리케이션 views.py 작성 및 모델 추가
wecode-bootcamp-korea/31-1st-Wesop-backend pull request #2
Opened 2022-03-30 07:11 UTC by hy6652

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 리스트 페이지에 들어갈 views.py를 작성했습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 프론트엔드와 대화해본 결과, 상품 메인 페이지에 있는 설명 문구와, 각 상품 카테고리별로 가지고 있는 문구 및 타이틀도 저희쪽에서 줘야 map 함수를 사용할 수 있다고 하셔서 models.py에 추가했습니다.
2. 모델의 내용을 바탕으로 views.py를 작성했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- get 할 때 ForeignKe를 가지는 컬럼에 대해서 어떻게 다뤄야 할 지 복습할 수 있었습니다.
- image url은 여러 개 들어올 수 있는데 그걸 리스트 컴프리헨션으로 어떻게 다뤄야 할지 다시 고민해볼 수 있었습니다.
- 프론트엔드와 소통하면서 어떤 식으로 데이터를 보내주면 좋을지 서로 얘기하고 조정해 나가는 과정을 통해 커뮤니케이션의 중요성을 다시 한 번 알게 됐습니다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-03-30 08:34 UTC, lordmyshepherd requested changes
마이너한 리뷰 남겨드려요!

2022-03-30 08:34 UTC, lordmyshepherd commented on products/models.py
category에 하위 컬럼으로 옮겨주세요-!
```suggestion
```

2022-03-30 08:34 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'result':result}, status=200)
```suggestion
# 1. query parameter를 url에서 꺼낼 수 있는 방법을 검색해보세요.
# "127.0.0.1:8000/products"
# "127.0.0.1:8000/products?category_id = 1" 

# 2. 모든 속성을 product부터 시작해서 가져올 수 있도록 수정해주세요~
# 3. for문을 list comphrehension으로 수정해주세요~

class ProductListView(View):
            def get(self, request):
        products = Product.objects.all()
        result = []

        for product in products:
            result.append({
                'category_id':Category.objects.get(id=product.category.id).id,
                'category_name':Category.objects.get(id=product.category.id).category_name,
                'category_description':ProductDescription.objects.get(id=product.category.id).list_description,
                'products':[
                    {
                        'badge':product.badge,
                        'product_name':product.name,
                        'size':product.size,
                        'price':product.price,
                        'product_url':[img.image_url for img in ProductImage.objects.all()]
                    }
                ]
            })
        return JsonResponse({'result':result}, status=200)
```

2022-04-01 05:30 UTC, hy6652 commented
피드백 반영해서 수정했습니다!

2022-04-02 07:11 UTC, hy6652 commented
url 설정 수정했습니다!

2022-04-02 09:42 UTC, lordmyshepherd requested changes

2022-04-02 09:42 UTC, lordmyshepherd commented on products/views.py
> +        } for product in products][offset:limit]
offset, limit을 붙이는 부분을 조금 더 고려해보면 좋을 것 같습니다.
offset, limit은 DB에 데이터를 조회할 때 걸어줘야 합니다. 그러나 지금은 데이터베이스에서 10000개를 조회한 후에 거기서 offset, limit으로 짤라서 보내주는 형태로 구현이 되어 있어요!

2022-04-02 09:42 UTC, lordmyshepherd commented on products/views.py
> +
```suggestion
        category_id = int(request.GET.get('category_id', None))
        offset = int(request.GET.get('offset', 0))
        limit = int(request.GET.get('limit', 0))

        if not category_id:
            products = Product.objects.all()
        else:
            products = Product.objects.filter(category=category_id)
```

2022-04-04 06:13 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-04-05 05:18 UTC, closed without merging