[ADD] product detail views.py 작성.
wecode-bootcamp-korea/31-1st-Wesop-backend pull request #5
Opened 2022-04-01 05:30 UTC by suhun96

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- product detail에 필요한 정보 및 사진을 DB로부터 프론트로 전달.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. detail : name, price, size, category, descriptrion, feeling ,product image , squence ,ingredient ,skin type
2. howtouse : 사용법, 사용량, 향 , 텍스처
3. recommend : 이름 , 사진 , 피부타입
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- url , query 파라미터를 적용하는데 많은 고생을 했으나 성공
- python을 이용한 csv 작성

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-01 09:51 UTC, suhun96 commented
피드백 내용 수정했습니다!

2022-04-01 21:28 UTC, lordmyshepherd requested changes

2022-04-01 21:28 UTC, lordmyshepherd commented on products/views.py
> +
빈 줄은 지워주세요~

2022-04-01 21:28 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message' : 'PRODUCT_NAME_ERROR'} , status = 401)
추천상품을 반환하는 엔드포인트는 새로 PR만들어서 올려주세요-!
한 PR에는 하나에 기능만 포함되어 있어야 합니다 👍🏻 

추가로 line 41에 삼항연산자가 반드시 필요한지 고민해보면 좋을 것 같습니다.

2022-04-02 07:19 UTC, suhun96 commented on products/views.py
> +            return JsonResponse({'message' : 'PRODUCT_NAME_ERROR'} , status = 401)
지우고 다시 올렸습니다!

2022-04-02 09:38 UTC, lordmyshepherd requested changes

2022-04-02 09:38 UTC, lordmyshepherd commented on products/views.py
> +
마지막으로 빈 줄 지워주시고, 컨플릭트 해결해주세요-!

2022-04-02 09:58 UTC, suhun96 commented on products/views.py
> +
컨플릭트 해결 하는 방법이 
1. 머지 후 해결한다
2. 해결 후 PR을 올린다.
둘 중에 뭐가 맞는건지 잘 모르겠습니다....

2022-04-02 12:39 UTC, suhun96 commented on products/views.py
> +
일단 github web에서 컴플릭트 수정해봤습니다 혹시 방법이 틀리면 바로 알려주세요

2022-04-04 06:29 UTC, closed without merging